Fix force close error : reproducing very rarely...
The reason looks that posted runnable is executed at bad timing (ex. task is cancelled or done or something else...)
To avoid this, start animation without 'posting'.
This doesn't make any problem at ICS or later. But due to Android's bug, this doesn't work at HC or below.
But, it's ok.
Target platform of FeedHive is ICS or later.

[ Function stack ]
java.lang.ClassCastException: android.graphics.drawable.BitmapDrawable cannot be cast to android.graphics.drawable.AnimationDrawable
at free.yhc.feeder.ItemListAdapter$2.run(ItemListAdapter.java:396)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4451)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
at dalvik.system.NativeStart.main(Native Method)